[package]
edition = "2018"
name = "xtask"
version = "0.1.0"
authors = ["Christoph Hegemann"]
publish = false
license = "MIT OR Apache-2.0"

[lib]

[dependencies]
anyhow = "1.0.26"
flate2 = "1.0"
pico-args = "0.3.1"
proc-macro2 = "1.0.8"
quote = "1.0.2"
ungrammar = "1.5"
walkdir = "2.3.1"
write-json = "0.1.0"
xshell = "0.1"
# Avoid adding more dependencies to this crate
